name: Deploy Go App to EC2

on:
  push:
    branches: [ master ] # Trigger the workflow on push to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'  # Specify the Go version you're using

      - name: Build
        run: |
          go build -v -o go-app-deploy github.com/integrationninjas/go-app
          ls -l  # List files to confirm the binary was created

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1  # Change this to your AWS region

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ec2-user
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          echo "Attempting to connect to $HOST as $USER..."
          ssh -i private_key -o StrictHostKeyChecking=no -vvv $USER@$HOST 'echo "Connection successful"'
          echo "SCP transfer..."
          scp -i private_key -o StrictHostKeyChecking=no go-app-deploy $USER@$HOST:~/
          echo "SSH and run..."
          ssh -i private_key -o StrictHostKeyChecking=no $USER@$HOST '
            pkill go-app-deploy || true
            nohup ./go-app-deploy > app.log 2>&1 &
            echo "Application started"
          '