name: Deploy to EC2

on:
  push:
    branches:
      - master # Make sure this matches the branch you're pushing to

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }} # Ensure this secret is set in GitHub

      - name: Add EC2 Host to Known Hosts
        run: |
          ssh-keyscan -H ec2-18-198-2-85.eu-central-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-18-198-2-85.eu-central-1.compute.amazonaws.com "cd /home/ec2-user/go-app && git pull origin main && go build -o main ./main.go && nohup ./main &"
