name: Deploy to EC2

on:
  push:
    branches:
      - master  # You can change this to the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build Go app
        run: |
          go build -o myapp main.go

      - name: Copy app to EC2 instance
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 35.156.115.105  # Your EC2 IP address
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}  # Private key stored in GitHub secrets
          port: 22
          source: ./myapp  # The app you built
          target: ~/go-app-deploy/myapp  # The target directory on the EC2 instance

      - name: Run app on EC2 instance
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 35.156.115.105  # Your EC2 IP address
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}  # Private key stored in GitHub secrets
          port: 22
          script: |
            cd ~/go-app-deploy
            chmod +x myapp
            ./myapp
          debug: true  # Optional, enable for more detailed output