name: Deploy Go App to EC2

on:
  push:
    branches: [ master ] # Trigger the workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'  # Specify the Go version you're using

      - name: Build
        run: go build -v github.com/integrationninjas/go-app  # Build your Go application

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1  # Change this to your AWS region

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ec2-user  # Change this if you're using a different user
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -i private_key -o StrictHostKeyChecking=no your-go-binary $USER@$HOST:~/
          ssh -i private_key -o StrictHostKeyChecking=no $USER@$HOST '
            pkill go-app-deploy || true
            nohup ./go-app-deploy > app.log 2>&1 &
          '