name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build the Go app
        run: go build -o go-app

      - name: Set correct permissions for SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

      - name: Copy app to EC2 instance
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: /tmp/ssh_key  # Use the temporary file with the correct key
          source: "./go-app"
          target: "~/go-app"

      - name: Restart app on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: /tmp/ssh_key  # Use the same key to SSH into EC2
          script: |
            pkill go-app || true
            nohup ~/go-app &
