name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build Go app
        run: |
          go build -o myapp main.go

      - name: Copy app to EC2 instance
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 35.156.115.105
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: ./myapp
          target: ~/myapp

      - name: Run app on EC2 instance
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 35.156.115.105
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          port: 22
          key_path: /tmp/id_rsa
          passphrase: ''
          use_insecure_cipher: true
          script: |
            cd ~/go-app-deploy
            chmod +x main
            ./main
          debug: true  # Enable debug mode for more info

# ec2-35-156-115-105.eu-central-1.compute.amazonaws.com
# 35.156.115.105
