name: Deploy to EC2

on:
  push:
    branches:
      - master  # Adjust this to the branch you want to auto-deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "${{ secrets.EC2_KEY }}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

      - name: Copy app to EC2 instance
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ec2-35-156-115-105.eu-central-1.compute.amazonaws.com
          username: ec2-user
          key: /tmp/ssh_key
          source: "./go-app-deploy"  # Adjust to your Go app folder
          target: "~/go-app-deploy"

      - name: Run Go app on EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ec2-35-156-115-105.eu-central-1.compute.amazonaws.com
          username: ec2-user
          key: /tmp/ssh_key
          script: |
            cd ~/go-app-deploy
            go build -o myapp .
            ./myapp  # Adjust this command to how you run your Go app
